const images = {
  common: {
    logoBlack: '/images/common/logo-black.png',
    logoWhite: '/images/common/logo-white.png',
    lightMode: '/images/common/ic-mode-light.png',
    darkMode: '/images/common/ic-mode-dark.png',
    profile: '/images/common/profile.png',
    name: '/images/common/ic-name.png',
    nameWhite: '/images/common/ic-name-white.png',
    graduation: '/images/common/ic-graduation.png',
    graduationWhite: '/images/common/ic-graduation-white.png',
    email: '/images/common/ic-email.png',
    emailWhite: '/images/common/ic-email-white.png',
    phone: '/images/common/ic-phone.png',
    phoneWhite: '/images/common/ic-phone-white.png',
  },
  logo: {
    react: '/images/logo/logo-react.png',
    nextJs: '/images/logo/logo-nextjs.png',
    javaScript: '/images/logo/logo-javascript.png',
    typeScript: '/images/logo/logo-typescript.png',
    recoil: '/images/logo/logo-recoil.png',
    redux: '/images/logo/logo-redux.png',
    sass: '/images/logo/logo-sass.png',
    styledComponents: '/images/logo/logo-styled-components.png',
    tailwindCss: '/images/logo/logo-tailwindcss.png',
    vueJs: '/images/logo/logo-vuejs.png',
    emotion: '/images/logo/logo-emotion.png',
    reactQuery: '/images/logo/logo-react-query.png',
    ssafy: '/images/logo/logo-ssafy.png',
    wim: '/images/logo/logo-wim.png',
  } as { [key: string]: string },
};

export default images;
