import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.css';
import RecoilContainer from '../_components/common/RecoilContainer';
import ThemeButton from '../_components/common/ThemeButton';
import Logo from '../_components/common/Logo';
import ThemeSettingScript from '../_components/common/ThemeSettingScript';

const notoSans = Noto_Sans({
  weight: ['300', '400', '500', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <RecoilContainer>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${notoSans.className} w-[100dvw] h-[100dvh] flex justify-center dark:bg-grey-900 dark:text-grey-50`}
        >
          <ThemeSettingScript />
          <main className="flex min-h-screen font-bold text-lg w-full">
            <Logo />
            <ThemeButton />
            {children}
          </main>
        </body>
      </html>
    </RecoilContainer>
  );
}
